
//   List MENU Type
export const GET_LIST_MENU = 'GET_LIST_MENU'
export const GET_LIST_MENU_FULFILLED = "GET_LIST_MENU_FULFILLED"
export const GET_LIST_MENU_REJECTED = "GET_LIST_MENU_REJECTED"


// for transaction reducer
export const SEND_TABLE_NUMBER = 'SEND_TABLE_NUMBER'
export const SEND_TABLE_NUMBER_FULFILLED = "SEND_TABLE_NUMBER_FULFILLED"
export const SEND_TABLE_NUMBER_REJECTED = 'SEND_TABLE_NUMBER_REJECTED'

// for order reducer
export const GET_LIST_ORDER = 'GET_LIST_ORDER'
export const SEND_ORDER = 'SEND_ORDER'
export const SEND_ORDER_FULFILLED = 'SEND_ORDER_FULFILLED'
export const SEND_ORDER_REJECTED = 'SEND_ORDER_REJECTED'



